title: Tomasz Szulc
email: mail@szulctomasz.com
description: "iOS Software Engineer. Swift. Objective-C. Programming. Tips. Tricks."

url: http://szulctomasz.com
baseurl: ""

twitter_username: tomkowz

markdown: kramdown
highlighter: rouge

gems:
  - jekyll-redirect-from
